### ISSUE TITLE
Investigación ANTLR4

### ISSUE THREAD

**Issue by Hrbacek** [UN-Compilers/lang#9]
Preparar un reporte sobre la funcionalidad de ANTLR4 para las tareas de crear el lexer y parser

**Comment by danilopedraza** [comment]
En particular, deberíamos conocer el formato en el que ANTLR nos pasa el árbol de parsing o el AST. Así podemos diseñar mocks de ellos y empezar a desarrollar el intérprete.

**Comment by danilopedraza** [comment]
En la reunión pasada (16 de noviembre) vimos como interactuar con el árbol generado por ANTLR con el sistema de Visitors/Listeners. También exploramos una librería para hacer mocks en Go. Creo que ya tenemos herramientas para simular un contexto de ANTLR y hacer pruebas.

**Comment by danilopedraza** [comment]
Como por ahora no requerimos de saber mucho más sobre ANTLR, voy a cerrar este issue.
